"use client";
import { useEffect, useState } from "react";
import { profileRepository } from "../../repositories/profile-repository";
import { supabaseProfileRepository } from "../../repositories/supabase-profile-repository";
import { isSupabaseConfigured } from "../../lib/supabase/config";
import { isDemoAccountId } from "../../data/demo-accounts";
import type { UserProfile } from "../../types/transactions";

const defaults: Record<"dealer" | "shop", UserProfile> = {
  dealer: { id: "hanjaejin-dealer", role: "dealer", name: "한재진", companyName: "카마스터 딜러", phone: "010-1234-5678", email: "dealer@car-master.kr", activityArea: "서울·경기", notifications: { request: true, chat: true, schedule: true, marketing: false } },
  shop: { id: "misa-starhills-shop", role: "shop", name: "미사 스타힐스 시공점", representativeName: "홍길동", phone: "031-000-0000", email: "shop@car-master.kr", address: "경기 하남시 미사강변중앙로 180", brands: ["버텍스", "솔라가드", "후퍼옵틱", "브이쿨"], works: ["썬팅", "신차검수", "PPF", "블랙박스"], hours: "평일 09:00-19:00", closedDays: "매주 일요일", emergencyAvailable: true, introduction: "신차 패키지 전문 시공점", notifications: { request: true, chat: true, schedule: true, marketing: false } },
};
export function ProfileEditor({ role, userId, activity }: { role: "dealer" | "shop"; userId?: string; activity: { total: number; monthly: number; completed: number; favorites: number } }) {
  const profileId = userId ?? defaults[role].id;
  const useMemberDatabase = isSupabaseConfigured && !isDemoAccountId(profileId);
  const [profile, setProfile] = useState(() => profileRepository.getById(profileId) ?? { ...defaults[role], id: profileId }); const [saved, setSaved] = useState(false); const [loading, setLoading] = useState(useMemberDatabase); const [error, setError] = useState("");
  useEffect(() => { if (!useMemberDatabase) return; void supabaseProfileRepository.getById(profileId, role).then((value) => { if (value) setProfile(value); }).catch(() => setError("회원 정보를 불러오지 못했습니다.")).finally(() => setLoading(false)); }, [profileId, role, useMemberDatabase]);
  const field = (key: keyof UserProfile, label: string) => <label>{label}<input value={Array.isArray(profile[key]) ? profile[key].join(", ") : String(profile[key] ?? "")} onChange={(event) => setProfile({ ...profile, [key]: key === "brands" || key === "works" ? event.target.value.split(",").map((item) => item.trim()).filter(Boolean) : event.target.value })} /></label>;
  if (loading) return <section className="profile-editor"><div className="empty-state"><h2>회원 정보를 불러오고 있습니다.</h2></div></section>;
  const save = async () => { setError(""); try { if (useMemberDatabase) await supabaseProfileRepository.save(profile); else profileRepository.save(profile); setSaved(true); } catch { setError("회원 정보를 저장하지 못했습니다."); } };
  return <section className="profile-editor"><div className="page-title"><div><p className="eyebrow">MY PAGE</p><h1>{role === "dealer" ? "딜러" : "시공점"} 마이페이지</h1><p className="page-subtitle">내 정보와 알림 설정, 최근 활동을 관리합니다.</p></div></div><section className="profile-activity-summary"><article><span>총 거래</span><b>{activity.total}건</b></article><article><span>이번 달 거래</span><b>{activity.monthly}건</b></article><article><span>완료 거래</span><b>{activity.completed}건</b></article><article><span>즐겨찾는 시공점</span><b>{activity.favorites}곳</b></article></section>{saved && <p className="profile-saved">회원 DB에 저장했습니다.</p>}{error && <p className="login-error">{error}</p>}<div className="profile-editor-grid">
    {role === "dealer" ? <>{field("name", "담당자명")}{field("companyName", "회사명")}{field("phone", "휴대전화")}{field("email", "이메일")}{field("activityArea", "기본 활동지역")}</> : <>{field("name", "시공점명")}{field("representativeName", "대표자명")}{field("address", "주소")}{field("phone", "전화번호")}{field("brands", "취급 브랜드")}{field("works", "가능 작업")}{field("hours", "영업시간")}{field("closedDays", "휴무일")}{field("introduction", "소개글")}<label className="profile-checkbox-field"><input type="checkbox" checked={Boolean(profile.emergencyAvailable)} onChange={(event) => setProfile({ ...profile, emergencyAvailable: event.target.checked })} /> 긴급 시공 요청을 받을 수 있습니다.</label></>}
  </div><section className="profile-notification-settings"><h2>알림 설정</h2>{(["request", "chat", "schedule", "marketing"] as const).map((key) => <label key={key}><input type="checkbox" checked={profile.notifications[key]} onChange={() => setProfile({ ...profile, notifications: { ...profile.notifications, [key]: !profile.notifications[key] } })} />{{ request: "시공 요청 응답", chat: "거래 채팅", schedule: "일정 및 상태", marketing: "서비스 소식" }[key]}</label>)}</section><div className="profile-editor-actions"><button className="primary" onClick={() => void save()}>변경사항 저장</button><button className="secondary" onClick={() => alert("비밀번호 재설정 기능은 이메일 인증 설정과 함께 제공될 예정입니다.")}>비밀번호 변경</button></div><p>{useMemberDatabase ? "회원 기본 정보는 안전한 회원 DB에 저장됩니다." : "시험 계정 정보는 현재 브라우저에 저장됩니다."}</p></section>;
}
